parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Notification\NotifierPort: '@App\Notification\LogNotifier'

    logger:
        class: Symfony\Component\HttpKernel\Log\Logger
        arguments:
            $minLevel: 'debug'
            $output: '%kernel.logs_dir%/%kernel.environment%.log'
